spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Task4?currentSchema=users
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: false
    contexts: dev

logging:
  level:
    liquibase: DEBUG
    org.liquibase: DEBUG
    org.springframework.liquibase: DEBUG